<?php


namespace App\Models\Admin;

use Illuminate\Database\QueryException;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Request;
use App\Models\VegetableLand as Base;

class VegetableLand extends Base
{
    const CREATED_AT = 'create_time';
    const UPDATED_AT = null;
    protected $dateFormat = 'U';
    protected $casts = [
        'create_time' => 'datetime:Y-m-d H:i:s',
    ];
    protected $table = "vegetable_land";
    protected $fillable = ['monitor', 'v_num', 'l_status'];

    public function getLStatusAttribute($value)
    {
        $arr = ["未使用", '已使用', "其他"];
        return $arr[$value];
    }
    public function creatLand(){
        try {
            DB::beginTransaction();
            //$this->monitor = Request::get('monitor');废弃
            $this->name =Request::get('name');
            $this->v_num =Request::get('v_num');
            $this->l_status =Request::get('l_status');
            $this->tx_video_url =Request::get('tx_video_url');
            $this->tx_video_id =Request::get('tx_video_id');

            $this->save();
            DB::commit();
            return true;
        }catch (QueryException $e){
            DB::rollBack();
            return $e->getMessage();
        }
    }
    public function editLand(){
        try {
            DB::beginTransaction();
            $land = $this->find(Request::input('id'));
            //$land->monitor = Request::input('monitor');废弃
            $this->name =Request::get('name');
            $land->v_num =Request::input('v_num');
            $land->l_status =Request::input('l_status');
            $this->tx_video_url =Request::get('tx_video_url');
            $this->tx_video_id =Request::get('tx_video_id');
            $land->save();
            DB::commit();
            return true;
        }catch (QueryException $e){
            DB::rollBack();
            return $e->getMessage();
        }
    }
    static function page()
    {
        return 'ok'; // TODO: Change the autogenerated stub
    }

}
